      

   RTM_EC_OK(0, "OK"),
   RTM_EC_INVALID_PID_OR_UID(200001, "RTM_EC_INVALID_PID_OR_UID"), //无效的项目id或 用户id
   RTM_EC_INVALID_PID_OR_SIGN(200002, "RTM_EC_INVALID_PID_OR_SIGN"), //无效的pid
   RTM_EC_INVALID_FILE_OR_SIGN_OR_TOKEN(200003, "RTM_EC_INVALID_FILE_OR_SIGN_OR_TOKEN"), //无效的filetoken
   RTM_EC_ATTRS_WITHOUT_SIGN_OR_EXT(200004, "RTM_EC_ATTRS_WITHOUT_SIGN_OR_EXT"), //file attrs错误
   RTM_EC_INVALID_MTYPE(200005, "RTM_EC_INVALID_MTYPE"), //错误的消息类型
   RTM_EC_SAME_SIGN(200006, "RTM_EC_SAME_SIGN"),
   RTM_EC_INVALID_FILE_MTYPE(200007, "RTM_EC_INVALID_FILE_MTYPE"),
   RTM_EC_INVALID_SERFVER_TIME (200008,"RTM_EC_INVALID_SERFVER_TIME"),//与服务器时间不匹配
   RTM_EC_FREQUENCY_LIMITED(200010, "RTM_EC_FREQUENCY_LIMITED"), //接口频率限制
   RTM_EC_REFRESH_SCREEN_LIMITED(200011, "RTM_EC_REFRESH_SCREEN_LIMITED"),
   RTM_EC_KICKOUT_SELF(200012, "RTM_EC_KICKOUT_SELF"),
   RTM_EC_FORBIDDEN_METHOD(200020, "RTM_EC_FORBIDDEN_METHOD"),//调用被禁止的方法
   RTM_EC_PERMISSION_DENIED(200021, "RTM_EC_PERMISSION_DENIED"),//没有权限
   RTM_EC_UNAUTHORIZED(200022, "RTM_EC_UNAUTHORIZED"), //用户没有验证
   RTM_EC_DUPLCATED_AUTH(200023, "RTM_EC_DUPLCATED_AUTH"),//用户重复验证
   RTM_EC_PROJECT_BLACKUSER(200024, "RTM_EC_PROJECT_BLACKUSER"),//用户被加入黑名单
   RTM_EC_ADMIN_LOGIN(200025, "RTM_EC_ADMIN_LOGIN"),//管理员登录
   RTM_EC_ADMIN_ONLY(200026, "RTM_EC_ADMIN_ONLY"),//不是管理员
   RTM_EC_INVALID_AUTH_TOEKN (200027,"RTM_EC_INVALID_AUTH_TOEKN"),//无效的token
   RTM_EC_LARGE_MESSAGE_OR_ATTRS(200030, "RTM_EC_LARGE_MESSAGE_OR_ATTRS"),//消息或attrs大小超过限制
   RTM_EC_LARGE_FILE_OR_ATTRS(200031, "RTM_EC_LARGE_FILE_OR_ATTRS"), //文件大小超限
   RTM_EC_TOO_MANY_ITEMS_IN_PARAMETERS(200032, "RTM_EC_TOO_MANY_ITEMS_IN_PARAMETERS"),//超过//添加/查询/删除 群组/房间/用户的集合大小
   RTM_EC_EMPTY_PARAMETER(200033, "RTM_EC_EMPTY_PARAMETER"),//目标集合为空
   RTM_EC_NOT_IN_ROOM(200040, "RTM_EC_NOT_IN_ROOM"),//没有在房间内
   RTM_EC_NOT_GROUP_MEMBER(200041, "RTM_EC_NOT_GROUP_MEMBER"),//不是群组成员
   RTM_EC_MAX_GROUP_MEMBER_COUNT(200042, "RTM_EC_MAX_GROUP_MEMBER_COUNT"),//群组成员已达最大值
   RTM_EC_NOT_FRIEND(200043, "RTM_EC_NOT_FRIEND"),//不是好友
   RTM_EC_BANNED_IN_GROUP(200044, "RTM_EC_BANNED_IN_GROUP"),//群组禁言
   RTM_EC_BANNED_IN_ROOM(200045, "RTM_EC_BANNED_IN_ROOM"),//房间禁言
   RTM_EC_EMPTY_GROUP(200046, "RTM_EC_EMPTY_GROUP"),//空群组
   RTM_EC_MAX_ROOM_COUNT(200047, "RTM_EC_MAX_ROOM_COUNT"),//房间已达上限
   RTM_EC_MAX_FRIEND_COUNT(200048, "RTM_EC_MAX_FRIEND_COUNT"),//好友已达上限
   RTM_EC_IN_BLACKLIST(200049, "RTM_EC_IN_BLACKLIST"),//用户在黑名单中
   RTM_EC_UNSUPPORTED_LANGUAGE(200050, "RTM_EC_UNSUPPORTED_LANGUAGE"),//不支持的语言
   RTM_EC_EMPTY_TRANSLATION(200051, "RTM_EC_EMPTY_TRANSLATION"),
   RTM_EC_SEND_TO_SELF(200052, "RTM_EC_SEND_TO_SELF"),//向自己发送消息
   RTM_EC_DUPLCATED_MID(200053, "RTM_EC_DUPLCATED_MID"),//重复的messageid
   RTM_EC_SENSITIVE_WORDS(200054, "RTM_EC_SENSITIVE_WORDS"),
   RTM_EC_NOT_ONLINE(200055, "RTM_EC_NOT_ONLINE"),//没有在线
   RTM_EC_TRANSLATION_ERROR(200056, "RTM_EC_TRANSLATION_ERROR"),//翻译错误
   RTM_EC_PROFANITY_STOP(200057, "RTM_EC_PROFANITY_STOP"),//非法图片语音视频等审核没通过
   RTM_EC_NO_CONFIG_IN_CONSOLE(200060, "RTM_EC_NO_CONFIG_IN_CONSOLE"),//控制台没有配置
   RTM_EC_NO_SUPPORT_TTPE(200061, "not supported transcribe type"),//未识别的语音类型
   RTM_EC_MESSAGE_NOT_FOUND(200070, "RTM_EC_MESSAGE_NOT_FOUND"),
   RTM_EC_UNKNOWN_ERROR(200999, "RTM_EC_UNKNOWN_ERROR");
